services:
  nginx-proxy:
    build: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment: 
      - FLASK_SERVER_ADDR=flask-app:8080
    ports:
      - "80:80"
    depends_on:
      - flask-app
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/api/v1.0/flask_health_check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh
  flask-app: 
    build:
      context: app
      target: builder
    stop_signal: SIGINT
    ports:
      - '8080:8080'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8080/api/v1.0/flask_health_check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:8080 app:app